import { useState, useEffect, useCallback, useRef } from "react";
import axios from "axios";
import { jsPDF } from "jspdf";
import Ic from "../icons";
import { useReveal } from "../hooks/useReveal";
import TiltCard from "../components/TiltCard";
import Btn from "../components/Btn";
import TrustGauge from "../components/TrustGauge";
import { backendUrl } from "../src/config";
import Footer from "../components/Footer";

const API = backendUrl;

const TYPE_LABELS = { text: "TEXT", image: "IMAGE", voice: "VOICE", ai_image: "AI DETECT" };
const TYPE_ICONS = { text: "Search", image: "Img", voice: "Mic", ai_image: "Eye" };
const FILTERS = [
  { value: "", label: "All" },
  { value: "text", label: "Text" },
  { value: "image", label: "Image" },
  { value: "voice", label: "Voice" },
  { value: "ai_image", label: "AI" },
];

// ─── FORMAT DATE ──────────────────────────────────────────────────────────────
function fmtDate(iso) {
  const d = new Date(iso);
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}
function fmtDateTime(iso) {
  const d = new Date(iso);
  return d.toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" });
}

// ─── PDF EXPORT FOR HISTORY ENTRY ─────────────────────────────────────────────
function exportEntryPdf(entry) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pw = 210, margin = 20, cw = pw - margin * 2;
  let y = margin;
  const addLine = () => { doc.setDrawColor(180); doc.setLineWidth(0.3); doc.line(margin, y, pw - margin, y); y += 4; };
  const heading = (text) => {
    if (y > 265) { doc.addPage(); y = margin; }
    doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(40, 40, 40);
    doc.text(text, margin, y); y += 6; addLine();
  };
  const body = (text) => {
    doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(60, 60, 60);
    const lines = doc.splitTextToSize(String(text || ""), cw);
    lines.forEach(ln => { if (y > 280) { doc.addPage(); y = margin; } doc.text(ln, margin, y); y += 5; });
    y += 2;
  };
  const bullet = (text) => {
    doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(60, 60, 60);
    const lines = doc.splitTextToSize(String(text || ""), cw - 6);
    lines.forEach((ln, idx) => { if (y > 280) { doc.addPage(); y = margin; } doc.text(idx === 0 ? `  - ${ln}` : `    ${ln}`, margin, y); y += 5; });
  };

  doc.setFont("helvetica", "bold"); doc.setFontSize(18); doc.setTextColor(109, 40, 217);
  doc.text("TruthLens AI Verification Report", pw / 2, y, { align: "center" }); y += 10; addLine(); y += 2;

  heading("REPORT METADATA");
  body(`Date: ${fmtDateTime(entry.createdAt)}`);
  body(`Input Type: ${TYPE_LABELS[entry.input_type] || entry.input_type}`); y += 2;

  heading("USER INPUT");
  body(entry.original_input || "N/A"); y += 2;

  heading("FINAL VERDICT");
  doc.setFont("helvetica", "bold"); doc.setFontSize(13); doc.setTextColor(109, 40, 217);
  doc.text(String(entry.verdict || "N/A").toUpperCase(), margin, y); y += 8;

  heading("CONFIDENCE SCORE");
  body(`${entry.confidence ?? "N/A"}%`); y += 2;

  heading("DETAILED ANALYSIS");
  body(entry.explanation || "No analysis available."); y += 2;

  if (entry.visual_inconsistencies?.length) {
    heading("VISUAL INCONSISTENCIES");
    entry.visual_inconsistencies.forEach(item => bullet(item)); y += 2;
  }
  if (entry.ai_generation_indicators?.length) {
    heading("AI GENERATION INDICATORS");
    entry.ai_generation_indicators.forEach(item => bullet(item)); y += 2;
  }
  if (entry.sources?.length) {
    heading("SOURCES");
    entry.sources.forEach(s => bullet(s)); y += 2;
  }

  heading("CONCLUSION");
  body(
    `Based on TruthLens AI analysis, the content was assessed as "${entry.verdict}" with ${entry.confidence}% confidence. ` +
    `This report was generated automatically for informational purposes.`
  );
  y += 6; addLine();
  doc.setFont("helvetica", "italic"); doc.setFontSize(8); doc.setTextColor(140, 140, 140);
  doc.text("Generated by TruthLens AI  |  Automated Forensic Verification Platform", pw / 2, y + 2, { align: "center" });

  doc.save(`TruthLens_Report_${new Date(entry.createdAt).toISOString().slice(0, 10)}.pdf`);
}

// ─── DETAIL MODAL ─────────────────────────────────────────────────────────────
function DetailModal({ entry, t, onClose, onExport, onDelete }) {
  if (!entry) return null;
  const col = entry.confidence >= 70 ? t.hi : entry.confidence >= 40 ? t.mid : t.lo;

  return (
    <div onClick={onClose} style={{
      position: "fixed", inset: 0, zIndex: 9000, background: "rgba(0,0,0,.55)", backdropFilter: "blur(8px)",
      display: "flex", alignItems: "center", justifyContent: "center", padding: 24,
    }}>
      <div onClick={e => e.stopPropagation()} style={{
        width: "100%", maxWidth: 680, maxHeight: "85vh", overflowY: "auto",
        background: t.bg, border: `1px solid ${t.border}`, borderRadius: 16, padding: 36,
        boxShadow: "0 24px 80px rgba(0,0,0,.4)",
      }}>
        {/* Header */}
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 24 }}>
          <div>
            <span style={{
              fontFamily: "'DM Mono',monospace", fontSize: 10, letterSpacing: ".14em",
              padding: "4px 12px", borderRadius: 14, background: t.accent + "15", color: t.accent, border: `1px solid ${t.accent}30`,
            }}>{TYPE_LABELS[entry.input_type]}</span>
            <div style={{ fontFamily: "'DM Mono',monospace", fontSize: 11, color: t.faint, marginTop: 10, display: "flex", alignItems: "center", gap: 6 }}>
              <Ic.Clock s={12} /> {fmtDateTime(entry.createdAt)}
            </div>
          </div>
          <button onClick={onClose} style={{ background: "none", border: "none", cursor: "pointer", color: t.muted, padding: 4 }}>
            <Ic.X s={20} />
          </button>
        </div>

        {/* Gauge */}
        <div style={{ display: "flex", justifyContent: "center", marginBottom: 24 }}>
          <TrustGauge score={entry.confidence} verdict={entry.verdict} t={t} />
        </div>

        {/* Verdict */}
        <div style={{
          textAlign: "center", fontFamily: "'Bebas Neue',sans-serif", fontSize: 32, letterSpacing: ".06em",
          color: col, marginBottom: 6,
        }}>{String(entry.verdict).toUpperCase()}</div>
        <div style={{
          textAlign: "center", fontFamily: "'DM Mono',monospace", fontSize: 12, color: t.faint, marginBottom: 28,
        }}>{entry.confidence}% confidence</div>

        {/* Input */}
        <div style={{ marginBottom: 20 }}>
          <div style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 16, letterSpacing: ".1em", color: t.text, marginBottom: 8 }}>INPUT</div>
          <div style={{
            fontFamily: "'Space Grotesk',sans-serif", fontSize: 13, color: t.muted, lineHeight: 1.7,
            padding: 16, background: t.input, borderRadius: 10, border: `1px solid ${t.line}`,
            maxHeight: 120, overflowY: "auto",
          }}>{entry.original_input || "N/A"}</div>
        </div>

        {/* Explanation */}
        <div style={{ marginBottom: 20 }}>
          <div style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 16, letterSpacing: ".1em", color: t.text, marginBottom: 8 }}>ANALYSIS</div>
          <div style={{
            fontFamily: "'Space Grotesk',sans-serif", fontSize: 13, color: t.muted, lineHeight: 1.7,
            padding: 16, background: t.input, borderRadius: 10, border: `1px solid ${t.line}`,
            maxHeight: 200, overflowY: "auto",
          }}>{entry.explanation || "No detailed analysis."}</div>
        </div>

        {/* Visual Inconsistencies */}
        {entry.visual_inconsistencies?.length > 0 && (
          <div style={{ marginBottom: 20 }}>
            <div style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 16, letterSpacing: ".1em", color: t.text, marginBottom: 8 }}>VISUAL INCONSISTENCIES</div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
              {entry.visual_inconsistencies.map((v, i) => (
                <span key={i} style={{
                  fontFamily: "'DM Mono',monospace", fontSize: 11, padding: "5px 12px", borderRadius: 16,
                  background: t.lo + "12", border: `1px solid ${t.lo}30`, color: t.lo, lineHeight: 1.4,
                }}>{v}</span>
              ))}
            </div>
          </div>
        )}

        {/* AI Generation Indicators */}
        {entry.ai_generation_indicators?.length > 0 && (
          <div style={{ marginBottom: 20 }}>
            <div style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 16, letterSpacing: ".1em", color: t.text, marginBottom: 8 }}>AI GENERATION INDICATORS</div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
              {entry.ai_generation_indicators.map((v, i) => (
                <span key={i} style={{
                  fontFamily: "'DM Mono',monospace", fontSize: 11, padding: "5px 12px", borderRadius: 16,
                  background: t.accent + "12", border: `1px solid ${t.accent}30`, color: t.accent, lineHeight: 1.4,
                }}>{v}</span>
              ))}
            </div>
          </div>
        )}

        {/* Sources */}
        {entry.sources?.length > 0 && (
          <div style={{ marginBottom: 24 }}>
            <div style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 16, letterSpacing: ".1em", color: t.text, marginBottom: 8 }}>SOURCES</div>
            {entry.sources.map((src, i) => (
              <a key={i} href={src} target="_blank" rel="noopener noreferrer"
                style={{
                  display: "block", fontFamily: "'DM Mono',monospace", fontSize: 11, color: t.accent,
                  textDecoration: "none", marginBottom: 6, wordBreak: "break-all", lineHeight: 1.5,
                }}>{src}</a>
            ))}
          </div>
        )}

        {/* Actions */}
        <div style={{ display: "flex", gap: 10, marginTop: 8 }}>
          <Btn t={t} sz="md" icon={<Ic.Download s={14} />} onClick={() => onExport(entry)} style={{ flex: 1, justifyContent: "center" }}>
            Export PDF
          </Btn>
          <Btn t={t} v="secondary" sz="md" icon={<Ic.Trash s={14} />} onClick={() => onDelete(entry._id)}
            style={{ flex: 1, justifyContent: "center", color: t.lo, borderColor: t.lo + "40" }}>
            Delete
          </Btn>
        </div>
      </div>
    </div>
  );
}

// ─── HISTORY ROW ──────────────────────────────────────────────────────────────
function HistRow({ item, t, i, vis, onClick }) {
  const [hov, setHov] = useState(false);
  const col = item.confidence >= 70 ? t.hi : item.confidence >= 40 ? t.mid : t.lo;
  const IcType = Ic[TYPE_ICONS[item.input_type]] || Ic.Search;

  return (
    <div
      onMouseEnter={() => setHov(true)} onMouseLeave={() => setHov(false)}
      onClick={onClick} data-mag
      style={{
        display: "flex", alignItems: "center", gap: 20, padding: "20px 22px",
        borderBottom: `1px solid ${t.line}`, cursor: "pointer",
        background: hov ? t.card : "transparent", borderRadius: hov ? 10 : 0,
        opacity: vis ? 1 : 0, transform: vis ? "translateY(0)" : "translateY(24px)",
        transition: `background .25s, border-radius .25s, opacity .8s ${.1 + i * .07}s cubic-bezier(0.16,1,0.3,1), transform .8s ${.1 + i * .07}s cubic-bezier(0.16,1,0.3,1)`,
      }}
    >
      {/* Score circle */}
      <span style={{
        width: 48, height: 48, borderRadius: "50%",
        background: col + "12", border: `2px solid ${col}40`, color: col,
        fontWeight: 900, fontSize: 13, fontFamily: "'Bebas Neue',sans-serif",
        letterSpacing: ".04em", display: "inline-flex", alignItems: "center", justifyContent: "center",
        flexShrink: 0, transition: "transform .3s", transform: hov ? "scale(1.1)" : "scale(1)",
      }}>{item.confidence}</span>

      {/* Type icon */}
      <div style={{
        width: 34, height: 34, borderRadius: 8, flexShrink: 0,
        background: t.accent + "10", border: `1px solid ${t.accent}20`,
        display: "flex", alignItems: "center", justifyContent: "center", color: t.accent,
      }}>
        <IcType s={16} />
      </div>

      {/* Text */}
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{
          fontFamily: "'Space Grotesk',sans-serif", fontSize: 14, fontWeight: 600, color: t.text,
          whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis",
        }}>
          {item.original_input?.slice(0, 80) || "No input"}
        </div>
        <div style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: t.faint, marginTop: 3, letterSpacing: ".12em" }}>
          {TYPE_LABELS[item.input_type]} &bull; {fmtDate(item.createdAt)}
        </div>
      </div>

      {/* Verdict badge */}
      <span style={{
        padding: "5px 14px", borderRadius: 20, fontSize: 10, fontWeight: 700,
        fontFamily: "'DM Mono',monospace", letterSpacing: ".1em", flexShrink: 0,
        background: col + "12", border: `1px solid ${col}35`, color: col,
      }}>{item.verdict}</span>

      {/* Arrow */}
      <div style={{
        color: t.faint, transform: hov ? "translateX(4px)" : "translateX(0)", transition: "transform .3s",
      }}>
        <Ic.Arr s={14} />
      </div>
    </div>
  );
}

// ─── EMPTY STATE ──────────────────────────────────────────────────────────────
function EmptyState({ t }) {
  return (
    <div style={{ textAlign: "center", padding: "80px 20px" }}>
      <div style={{ color: t.faint, marginBottom: 16 }}><Ic.Shield s={60} /></div>
      <div style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 28, color: t.muted, letterSpacing: ".06em", marginBottom: 8 }}>
        NO ANALYSES YET
      </div>
      <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: 14, color: t.faint, maxWidth: 400, margin: "0 auto", lineHeight: 1.6 }}>
        Run your first fact-check, image analysis, or voice verification and it will appear here automatically.
      </div>
    </div>
  );
}

// ─── MAIN: HISTORY PAGE ───────────────────────────────────────────────────────
export default function HistoryPage({ t, setPage }) {
  const [hRef, hVis] = useReveal(0.04);
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [pagination, setPagination] = useState({ page: 1, pages: 1, total: 0 });
  const [typeFilter, setTypeFilter] = useState("");
  const [search, setSearch] = useState("");
  const [searchInput, setSearchInput] = useState("");
  const [selected, setSelected] = useState(null);
  const searchTimer = useRef(null);

  // ── Fetch ──
  const fetchHistory = useCallback(async (pg = 1, type = typeFilter, q = search) => {
    setLoading(true);
    try {
      const params = { page: pg, limit: 20 };
      if (type) params.type = type;
      if (q) params.search = q;
      const { data } = await axios.get(`${API}/api/history`, { params });
      if (data.success) {
        setItems(data.data);
        setPagination(data.pagination);
      }
    } catch {
      setItems([]);
    } finally {
      setLoading(false);
    }
  }, [typeFilter, search]);

  useEffect(() => { fetchHistory(1); }, [typeFilter, search]);

  // ── Search debounce ──
  const onSearchChange = (val) => {
    setSearchInput(val);
    clearTimeout(searchTimer.current);
    searchTimer.current = setTimeout(() => setSearch(val), 400);
  };

  // ── Delete ──
  const handleDelete = async (id) => {
    try {
      await axios.delete(`${API}/api/history/${id}`);
      setItems(prev => prev.filter(i => i._id !== id));
      setPagination(prev => ({ ...prev, total: prev.total - 1 }));
      if (selected?._id === id) setSelected(null);
    } catch { /* silent */ }
  };

  // ── Clear all ──
  const handleClearAll = async () => {
    if (!confirm("Clear all history? This cannot be undone.")) return;
    try {
      await axios.delete(`${API}/api/history/clear`);
      setItems([]);
      setPagination({ page: 1, pages: 1, total: 0 });
    } catch { /* silent */ }
  };

  // ── Stats ──
  const stats = [
    { v: pagination.total, l: "TOTAL", c: t.accent },
    { v: items.filter(i => i.input_type === "text").length, l: "TEXT", c: t.hi },
    { v: items.filter(i => i.input_type === "image" || i.input_type === "ai_image").length, l: "IMAGE", c: t.mid },
    { v: items.filter(i => i.input_type === "voice").length, l: "VOICE", c: t.lo },
  ];

  return (
    <div className="responsive-page-container" style={{ paddingTop: 84, minHeight: "100vh", padding: "90px 60px", position: "relative", zIndex: 1 }}>


      {/* MODAL */}
      <DetailModal
        entry={selected} t={t}
        onClose={() => setSelected(null)}
        onExport={exportEntryPdf}
        onDelete={handleDelete}
      />

      {/* BACK */}
      <button onClick={() => setPage("landing")} data-mag style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "6px 14px", borderRadius: 8, border: `1px solid ${t.border}`, background: "transparent", color: t.muted, fontFamily: "'DM Mono',monospace", fontSize: 10, letterSpacing: ".08em", cursor: "pointer", transition: "all .25s", marginBottom: 20 }} onMouseEnter={e => { e.currentTarget.style.color = t.accent; e.currentTarget.style.borderColor = t.accent + "50"; }} onMouseLeave={e => { e.currentTarget.style.color = t.muted; e.currentTarget.style.borderColor = t.border; }}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="19 12 5 12" /><polyline points="12 19 5 12 12 5" /></svg>BACK</button>

      {/* TITLE */}
      <div style={{
        fontFamily: "'Bebas Neue',sans-serif", fontSize: "clamp(48px,7vw,80px)",
        letterSpacing: ".03em", color: t.text, lineHeight: .95, marginBottom: 10,
        opacity: hVis ? 1 : 0, transform: hVis ? "translateY(0)" : "translateY(40px)",
        transition: "all 1s .05s cubic-bezier(0.16,1,0.3,1)",
      }}>
        Analysis History
      </div>
      <p style={{
        fontFamily: "'Space Grotesk',sans-serif", color: t.muted, fontSize: 15, marginBottom: 36,
        opacity: hVis ? 1 : 0, transform: hVis ? "translateY(0)" : "translateY(30px)",
        transition: "all 1s .12s cubic-bezier(0.16,1,0.3,1)",
      }}>
        Your recent misinformation checks
      </p>

      {/* STATS */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 12, marginBottom: 32 }}>
        {stats.map((s, i) => (
          <TiltCard key={s.l} t={t} style={{
            padding: "20px 22px",
            opacity: hVis ? 1 : 0, transform: hVis ? "translateY(0)" : "translateY(22px)",
            transition: `all .8s ${.18 + i * .08}s cubic-bezier(0.16,1,0.3,1)`,
          }}>
            <div style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 48, letterSpacing: ".04em", color: s.c, lineHeight: 1 }}>{s.v}</div>
            <div style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: t.faint, letterSpacing: ".18em", marginTop: 3 }}>{s.l}</div>
          </TiltCard>
        ))}
      </div>

      {/* TOOLBAR: search + filter + clear */}
      <div style={{
        display: "flex", alignItems: "center", gap: 12, marginBottom: 20, flexWrap: "wrap",
        opacity: hVis ? 1 : 0, transform: hVis ? "translateY(0)" : "translateY(18px)",
        transition: "all .8s .3s cubic-bezier(0.16,1,0.3,1)",
      }}>
        {/* Search */}
        <div style={{
          flex: 1, minWidth: 200, display: "flex", alignItems: "center", gap: 10,
          background: t.input, border: `1px solid ${t.line}`, borderRadius: 10, padding: "10px 16px",
        }}>
          <Ic.Search s={14} />
          <input
            value={searchInput}
            onChange={e => onSearchChange(e.target.value)}
            placeholder="Search history..."
            style={{
              flex: 1, background: "transparent", border: "none", outline: "none",
              color: t.text, fontFamily: "'Space Grotesk',sans-serif", fontSize: 13,
            }}
          />
        </div>

        {/* Type filter pills */}
        <div style={{ display: "flex", gap: 6 }}>
          {FILTERS.map(f => (
            <button
              key={f.value} onClick={() => setTypeFilter(f.value)}
              style={{
                fontFamily: "'DM Mono',monospace", fontSize: 10, letterSpacing: ".1em",
                padding: "8px 16px", borderRadius: 20, cursor: "pointer",
                border: `1px solid ${typeFilter === f.value ? t.accent + "50" : t.line}`,
                background: typeFilter === f.value ? t.accent + "15" : "transparent",
                color: typeFilter === f.value ? t.accent : t.muted,
                transition: "all .2s",
              }}
            >{f.label}</button>
          ))}
        </div>

        {/* Clear all */}
        {items.length > 0 && (
          <button
            onClick={handleClearAll}
            style={{
              fontFamily: "'DM Mono',monospace", fontSize: 10, letterSpacing: ".1em",
              padding: "8px 16px", borderRadius: 20, cursor: "pointer", display: "inline-flex", alignItems: "center", gap: 6,
              border: `1px solid ${t.lo}30`, background: t.lo + "10", color: t.lo,
              transition: "all .2s",
            }}
          >
            <Ic.Trash s={11} /> CLEAR ALL
          </button>
        )}
      </div>

      {/* LIST */}
      <div ref={hRef} style={{ borderTop: `1px solid ${t.line}` }}>
        {loading ? (
          <div style={{ textAlign: "center", padding: "60px 0" }}>
            <div style={{
              width: 36, height: 36, border: `3px solid ${t.line}`, borderTop: `3px solid ${t.accent}`,
              borderRadius: "50%", animation: "spin 1s linear infinite", margin: "0 auto 16px",
            }} />
            <div style={{ fontFamily: "'DM Mono',monospace", fontSize: 12, color: t.faint, letterSpacing: ".15em" }}>
              LOADING HISTORY...
            </div>
          </div>
        ) : items.length === 0 ? (
          <EmptyState t={t} />
        ) : (
          items.map((item, i) => (
            <HistRow key={item._id} item={item} t={t} i={i} vis={hVis} onClick={() => setSelected(item)} />
          ))
        )}
      </div>

      {/* PAGINATION */}
      {pagination.pages > 1 && (
        <div style={{
          display: "flex", justifyContent: "center", alignItems: "center", gap: 12, marginTop: 32,
        }}>
          <Btn t={t} v="secondary" sz="sm"
            disabled={pagination.page <= 1}
            onClick={() => fetchHistory(pagination.page - 1)}
          >Prev</Btn>
          <span style={{ fontFamily: "'DM Mono',monospace", fontSize: 12, color: t.faint, letterSpacing: ".12em" }}>
            {pagination.page} / {pagination.pages}
          </span>
          <Btn t={t} v="secondary" sz="sm"
            disabled={pagination.page >= pagination.pages}
            onClick={() => fetchHistory(pagination.page + 1)}
          >Next</Btn>
        </div>
      )}

      <Footer t={t} setPage={setPage} />
    </div>
  );
}
